version: '3'

services:
  app:
    image: alexjray/instawatch-web-app:version1.0
    links:
      - db
    depends_on:
      - db
    expose:
      - "8080"
    ports:
      - 8080:8080
      - "8443:443"
    environment:
      - CORS_ORIGIN=http://localhost:8080
      - DATABASE_URL=postgres://postgres@db:5432/dev
      - DATABASE_DEBUG=false
      - SESSION_SECRET="d3bcddbf-3687-45c4-bc8d-81b6ac34edfd"
      - PORT=8080
      - PROTOCOL=http
    user: node

    command: npm start
  db:
    image: postgres:9.6.3-alpine
    tmpfs:
      - /tmp
      - /var/run/postgresql
    volumes:
      - db:/var/lib/postgresql/data
      - ./src/database/config/postgres-initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
volumes:
  db:
